eol = true
name = "node"
title = "Node.js"
intersphinx = [
    "https://mongodb.com/docs/manual/objects.inv",
    "https://mongodb.com/docs/drivers/objects.inv",
]

toc_landing_pages = [
    "/fundamentals/authentication",
    "/fundamentals",
    "/fundamentals/connection",
    "/fundamentals/crud",
    "/fundamentals/bson",
    "/usage-examples",
]
sharedinclude_root = "https://raw.githubusercontent.com/10gen/docs-shared/main/"


[constants]
version = "3.7"
package-name-org = "mongodb-org"
pgp-version = "{+version+}"
api = "http://mongodb.github.io/node-mongodb-native/{+version+}/api"
mongosh = "``mongosh``"
driver = "node"
driver-long = "MongoDB Node.js driver"
driver-short = "Node.js driver"
stable-api = "Stable API"
current-url-base = "https://www.mongodb.com/docs/drivers/node/current"

[[banners]]
targets = ["*"]
variant = "info"
value = """\
    This version of the documentation is archived and no longer supported. View the `current documentation <{+current-url-base+}>`__ to learn how to `upgrade your version of the {+driver-long+} <{+current-url-base+}/upgrade/>`__.\
    """
